### ISSUE TITLE
Verify the test device on sample app

### ISSUE THREAD

**Issue by TadashiSatoo** [google-home/sample-app-for-matter-android#83]
I installed GHSAFM-1.3.0default.
I try commissioning to nRF52840 DK bord.(Nordic) Device type is Lock.
Result is commissioning error on following.
> E/SetupDeviceViewModel: Commissioning failed with state Attestation failure. [CONTEXT service_id=336 ]
<img width="334" alt="JpHistory" src="https://user-images.githubusercontent.com/108783164/219284204-e0b23e62-aee7-4513-8e68-aab29c926b09.png">

What do modify on sample app code for success commissioning.
Google Home App is successful on DK bord.

I attached commissioning log.
[commissioning.log](https://github.com/google-home/sample-app-for-matter-android/files/10752778/commissioning.log)

Thank you for your support.

**Comment by pierredelisle** [comment]
I looked at the log file and do not see any logs related to GHSAFM. Are these logs for GHA instead?
At any rate, what certificate is used on the device? Attestation failed so there is an issue with the certificate.

```
2023-02-16 14:56:22.489 13598-13598/? E/SetupDeviceViewModel: Commissioning failed with state Attestation failure. [CONTEXT service_id=336 ]\
    m.eme: Device did not pass attestation (error(s)=[10, 5])\
        at m.enh.g(:com.google.android.gms.optional_home@230413065@23.04.13 (100400-0):36)\
        at m.enb.b(:com.google.android.gms.optional_home@230413065@23.04.13 (100400-0):0)\
        at m.nne.f(:com.google.android.gms.optional_home@230413065@23.04.13 (100400-0):4)\
        at m.nuo.run(:com.google.android.gms.optional_home@230413065@23.04.13 (100400-0):8)\
        at android.os.Handler.handleCallback(Handler.java:942)\
        at android.os.Handler.dispatchMessage(Handler.java:99)\
        at android.os.Looper.loopOnce(Looper.java:201)\
        at android.os.Looper.loop(Looper.java:288)\
        at android.app.ActivityThread.main(ActivityThread.java:7872)\
        at java.lang.reflect.Method.invoke(Native Method)\
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)\
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)\
2023-02-16 14:56:22.490 13598-13598/? E/SetupDeviceChimeraActiv: Showing error status. [CONTEXT service_id=336 ]\
    m.flw: Device did not pass attestation (error(s)=[10, 5])\
        at m.fta.a(:com.google.android.gms.optional_home@230413065@23.04.13 (100400-0):12)\
        at m.obf.a(:com.google.android.gms.optional_home@230413065@23.04.13 (100400-0):0)\
        at m.obe.a(:com.google.android.gms.optional_home@230413065@23.04.13 (100400-0):7)\
        at m.edo.b(:com.google.android.gms.optional_home@230413065@23.04.13 (100400-0):87)\
        at m.nne.f(:com.google.android.gms.optional_home@230413065@23.04.13 (100400-0):4)\
        at m.nuo.run(:com.google.android.gms.optional_home@230413065@23.04.13 (100400-0):7)\
        at android.os.Handler.handleCallback(Handler.java:942)\
        at android.os.Handler.dispatchMessage(Handler.java:99)\
        at android.os.Looper.loopOnce(Looper.java:201)\
        at android.os.Looper.loop(Looper.java:288)\
        at android.app.ActivityThread.main(ActivityThread.java:7872)\
        at java.lang.reflect.Method.invoke(Native Method)\
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)\
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)\
     Caused by: m.eme: Device did not pass attestation (error(s)=[10, 5])\
        at m.enh.g(:com.google.android.gms.optional_home@230413065@23.04.13 (100400-0):36)\
        at m.enb.b(:com.google.android.gms.optional_home@230413065@23.04.13 (100400-0):0)\
        at m.nne.f(:com.google.android.gms.optional_home@230413065@23.04.13 (100400-0):4)\
        at m.nuo.run(:com.google.android.gms.optional_home@230413065@23.04.13 (100400-0):8)\
        at android.os.Handler.handleCallback(Handler.java:942)\'a0\
        at android.os.Handler.dispatchMessage(Handler.java:99)\'a0\
        at android.os.Looper.loopOnce(Looper.java:201)\'a0\
        at android.os.Looper.loop(Looper.java:288)\'a0\
        at android.app.ActivityThread.main(ActivityThread.java:7872)\'a0\
        at java.lang.reflect.Method.invoke(Native Method)\'a0\
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)\'a0\
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)\'a0\

```

**Comment by TadashiSatoo** [comment]
Thank you for reply.
Sorry,log was not enough.Re attached log,but result is same.
[commissioning.log](https://github.com/google-home/sample-app-for-matter-android/files/10779684/commissioning.log)

I used not certification device.
Does sample app succeed only on certification devices?

I try GHA,it is successful on not certification device.
What changes should be made to the sample app for same as result on GHA?

**Comment by pierredelisle** [comment]
If the device is not a "test device", then attestation will fail.
The Matter SDK now makes it possible to bypass attestation verification. I'll work on a PR to support bypassing attestation verification.

**Comment by pierredelisle** [comment]
PR #92 has been merged and should fix this issue.

**Comment by TadashiSatoo** [comment]
@pierredelisle 
This problem is not fixed.
I commented following.
https://github.com/google-home/sample-app-for-matter-android/pull/92#issuecomment-1451383727
